### ISSUE TITLE
[Error] How to check Permission 

### ISSUE THREAD

**Issue by songyiYu** [flutter-moum/flutter_screenshot_callback#15]
I've tested this plugin refer to example/lib/main.dart

But I can't find where PermissionHandler is.

<img width="658" alt="스크린샷 2019-10-19 오후 2 41 45" src="https://user-images.githubusercontent.com/9947963/67138477-99b3a880-f27e-11e9-8327-3281eb7b5966.png">

How to solve it?

**Comment by kwanguuuu** [comment]
Thank you for this issue.

The ' example/lib/main.dart ' had to use [permission_handler plugin](https://pub.dev/packages/permission_handler#-readme-tab-) for permission. 

```PermissionHandler``` is from permission_handler package,
so you need to add dependencies in your /example/pubspec.yaml
```
dependencies:
  permission_handler: ^3.3.0

``` 
(Because we wanted to people use lots of plugin for activation)

But it made you hard to understand how to run example.dart.
We couldn't notice the problem. Sorry about it.

Now, we changed our lib dependencies, and it will help to use this plugin easily.
Check this commit 1e5bdad2feaa75c7bceba980aacc733a22d0a766, and plz update your plugin follow [this](https://pub.dev/packages/screenshot_callback#-installing-tab-)

Thank you
